# http://module-build.sourceforge.net/META-spec.html
name:         Mail-Webmail-Gmail
version:      0.06
version_from: lib/Mail/Webmail/Gmail.pm
license:      perl
requires:
        LWP::UserAgent   0
        HTTP::Headers    0
        HTTP::Cookies    0
        Crypt::SSLeay    0
        Exporter         0
        lib              0
        strict           0
distribution_type: module
